# Generated by Django 2.2.10 on 2020-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhayal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
