# Generated by Django 2.2.10 on 2020-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhayal', '0002_queries_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='answer',
            field=models.TextField(default='Not Answered Yet'),
        ),
    ]
